# Generated by Django 2.1.1 on 2018-10-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attempt_connect', models.BooleanField(default=False)),
                ('is_attempt_disconnect', models.BooleanField(default=False)),
                ('is_attempt_arm', models.BooleanField(default=False)),
                ('is_attempt_disarm', models.BooleanField(default=True)),
                ('connection_port', models.TextField(default='tcp:127.0.0.1:5760')),
            ],
        ),
        migrations.CreateModel(
            name='DroneStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_armed', models.BooleanField(default=False)),
                ('is_arming', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_connecting', models.BooleanField(default=False)),
                ('is_armable', models.BooleanField(default=False)),
                ('arm_status_message', models.TextField(default='')),
                ('connection_status_message', models.TextField(default='')),
                ('heading', models.TextField(default='')),
                ('last_heartbeat', models.FloatField(default=0)),
                ('_heartbeat_lastreceived', models.FloatField(default=0)),
                ('_heartbeat_timeout', models.BooleanField(default=True)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='copter.AerialPosition')),
                ('home_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_location', to='copter.AerialPosition')),
            ],
        ),
        migrations.CreateModel(
            name='FlightMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mission_running', models.BooleanField(default=False)),
                ('is_attempt_mission', models.BooleanField(default=False)),
                ('is_pause_mission', models.BooleanField(default=False)),
                ('mission_status_message', models.TextField(default='No message')),
                ('current_guided_waypoint', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='guided_waypoint', to='copter.AerialPosition')),
                ('waypoint_list', models.ManyToManyField(related_name='waypoint_list', to='copter.Waypoint')),
            ],
        ),
        migrations.DeleteModel(
            name='MavlinkArm',
        ),
        migrations.DeleteModel(
            name='MavlinkConnect',
        ),
        migrations.DeleteModel(
            name='MavlinkData',
        ),
        migrations.DeleteModel(
            name='MavlinkEngine',
        ),
        migrations.RemoveField(
            model_name='mavlinkgoto',
            name='guided_waypoint_list',
        ),
        migrations.RemoveField(
            model_name='mavlinkmission',
            name='waypoint_list',
        ),
        migrations.DeleteModel(
            name='MavlinkGoTo',
        ),
        migrations.DeleteModel(
            name='MavlinkMission',
        ),
    ]
