# Generated by Django 2.1.1 on 2018-09-28 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copter', '0002_auto_20180928_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronestatus',
            name='firmware_version',
        ),
        migrations.AlterField(
            model_name='dronestatus',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='copter.AerialPosition'),
        ),
        migrations.AlterField(
            model_name='dronestatus',
            name='home_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_location', to='copter.AerialPosition'),
        ),
        migrations.AlterField(
            model_name='guidedwaypoint',
            name='current_guided_waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_waypoint', to='copter.AerialPosition'),
        ),
    ]
