# Generated by Django 2.1.1 on 2018-10-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copter', '0002_auto_20181009_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightmission',
            name='is_mission_accomplished',
            field=models.BooleanField(default=False),
        ),
    ]
