# Generated by Django 2.1.1 on 2018-09-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copter', '0004_dronecommand_is_attempt_disconnect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronecommand',
            name='connection_baud_rate',
        ),
        migrations.AlterField(
            model_name='dronecommand',
            name='connection_port',
            field=models.TextField(default='tcp:127.0.0.1:5760'),
        ),
        migrations.AlterField(
            model_name='dronecommand',
            name='is_attempt_disarm',
            field=models.BooleanField(default=True),
        ),
    ]
