# Generated by Django 2.1.1 on 2018-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copter', '0005_auto_20180929_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronestatus',
            name='is_armable',
            field=models.BooleanField(default=False),
        ),
    ]
