# Generated by Django 2.1.1 on 2018-10-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copter', '0006_dronestatus_is_armable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronecommand',
            name='is_attempt_disconnect',
        ),
    ]
