# Generated by Django 2.1.1 on 2018-10-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copter', '0007_remove_dronecommand_is_attempt_disconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronecommand',
            name='is_attempt_disconnect',
            field=models.BooleanField(default=False),
        ),
    ]
